# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 225f7805d7135d241561859b87b3a941d88b565a240493e7dbf64848e702f0cab915056ece0ff37d186ef1c163ca799346d095555f749e7c5c15dc3a428f6663

test:
  secret_key_base: 2cbf856d7c4aa5bcf4a012ad0f5e6ec7da77052235584a6e7b1de29c0d3cbd9336f575ec2352539c8898e5a2815ce89dfd4f61195b3af13d5834bed7e4faa4c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
